// ============================================================
// FIREBASE CONFIGURATION
// ============================================================
// This file should be generated by running:
//   flutterfire configure
//
// Replace the placeholder values below with your actual Firebase
// project configuration. The FlutterFire CLI will auto-generate
// this file with your project's credentials.
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for Kigali City Services
  // Generated from google-services.json for Android
  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWOtkzcbWUh1waoaI5-HO4SOxcvqIyzrE',
    appId: '1:133751263072:android:2e268b7407cda9dd395805',
    messagingSenderId: '133751263072',
    projectId: 'kigalicityservices-1e070',
    storageBucket: 'kigalicityservices-1e070.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOtkzcbWUh1waoaI5-HO4SOxcvqIyzrE',
    appId: '1:133751263072:ios:a1d49d1d6f85ed0f395805',
    messagingSenderId: '133751263072',
    projectId: 'kigalicityservices-1e070',
    storageBucket: 'kigalicityservices-1e070.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOtkzcbWUh1waoaI5-HO4SOxcvqIyzrE',
    appId: '1:133751263072:web:3e9f8d7b5c4a2f1e0d9c8b',
    messagingSenderId: '133751263072',
    projectId: 'kigalicityservices-1e070',
    storageBucket: 'kigalicityservices-1e070.firebasestorage.app',
    authDomain: 'kigalicityservices-1e070.firebaseapp.com',
  );
}
